name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: blog_db
          POSTGRES_USER: blog_user
          POSTGRES_PASSWORD: blog_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          while ! nc -z localhost 5432; do sleep 1; done

      - name: Run Django Tests inside container
        run: docker-compose exec -T web python manage.py test

      - name: Shut down Docker Compose
        if: always()
        run: docker-compose down
