name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" > .env

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          TAG=${GITHUB_SHA::8}
          docker build -t zahid03/blog_api:$TAG .
          docker push zahid03/blog_api:$TAG

      - name: Deploy with Docker Compose
        run: |
          docker compose up -d --build
