name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted   # <-- Use your self-hosted runner

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t zahid03/blog_api:${GITHUB_SHA::8} .

      - name: Push Docker image
        run: docker push zahid03/blog_api:${GITHUB_SHA::8}
